// Mock data for demo purposes
import { User, Mission, Letter, Post, Comment } from '@/types';

export const mockUser: User = {
  id: 'mock-user-1',
  email: 'demo@mindsos.com',
  displayName: '데모 사용자',
  photoURL: '',
  streak: 7,
  lastCheckIn: new Date(),
  createdAt: new Date(),
};

export const mockMissions: Mission[] = [
  {
    id: 'mission-1',
    userId: 'mock-user-1',
    title: '아침 명상 10분',
    completed: true,
    recurring: true,
    createdAt: new Date(),
  },
  {
    id: 'mission-2',
    userId: 'mock-user-1',
    title: '감사 일기 작성',
    completed: true,
    recurring: true,
    createdAt: new Date(),
  },
  {
    id: 'mission-3',
    userId: 'mock-user-1',
    title: '가벼운 산책 30분',
    completed: false,
    recurring: true,
    createdAt: new Date(),
  },
  {
    id: 'mission-4',
    userId: 'mock-user-1',
    title: '물 8잔 마시기',
    completed: false,
    recurring: true,
    createdAt: new Date(),
  },
];

export const mockLetters: Letter[] = [
  {
    id: 'letter-1',
    userId: 'mock-user-1',
    title: '최근 스트레스에 대하여',
    content: '요즘 일 때문에 스트레스를 많이 받고 있어요. 어떻게 하면 좋을까요?',
    isPrivate: false,
    aiResponse: '스트레스를 받을 때는 잠시 멈추고 심호흡을 해보세요. 규칙적인 운동과 충분한 수면이 도움이 됩니다. 자신에게 너무 가혹하지 마세요.',
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'letter-2',
    userId: 'mock-user-1',
    title: '감사한 일들',
    content: '오늘은 따뜻한 햇살과 맛있는 커피에 감사했어요.',
    isPrivate: true,
    aiResponse: '감사의 마음을 표현하는 것은 정신 건강에 매우 좋습니다. 작은 것에 감사하는 마음을 계속 유지하세요.',
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(Date.now() - 172800000),
  },
  {
    id: 'letter-3',
    userId: 'other-user',
    title: '불안감 극복하기',
    content: '불안감이 들 때마다 어떻게 대처해야 할지 모르겠어요.',
    isPrivate: false,
    aiResponse: '불안감은 자연스러운 감정입니다. 마음챙김 명상이나 호흡 운동을 시도해보세요.',
    createdAt: new Date(Date.now() - 259200000),
    updatedAt: new Date(Date.now() - 259200000),
  },
  {
    id: 'letter-4',
    userId: 'mock-user-1',
    title: '인간관계가 어려워요',
    content: '사람들과 어울리는 게 점점 힘들어지고 있어요. 혼자 있는 게 더 편한데 이게 맞는 건가요?',
    isPrivate: false,
    aiResponse: '혼자만의 시간이 필요한 것은 자연스러운 일이에요. 하지만 의미 있는 관계는 삶을 풍요롭게 만들어줍니다. 무리하지 말고 자신의 속도대로 천천히 관계를 만들어가세요.',
    createdAt: new Date(Date.now() - 345600000),
    updatedAt: new Date(Date.now() - 345600000),
  },
  {
    id: 'letter-5',
    userId: 'other-user-10',
    title: '새로운 시작이 두려워요',
    content: '이직을 준비하고 있는데 새로운 환경이 너무 두렵습니다. 실패할까봐 걱정돼요.',
    isPrivate: false,
    aiResponse: '새로운 시작이 두려운 것은 당연합니다. 하지만 그 두려움은 성장의 신호이기도 해요. 작은 단계부터 시작하고, 실패해도 괜찮다는 마음가짐을 가져보세요.',
    createdAt: new Date(Date.now() - 432000000),
    updatedAt: new Date(Date.now() - 432000000),
  },
  {
    id: 'letter-6',
    userId: 'mock-user-1',
    title: '완벽주의를 버리고 싶어요',
    content: '모든 일을 완벽하게 해야 한다는 강박이 있어요. 조금만 실수해도 자책하게 돼요.',
    isPrivate: true,
    aiResponse: '완벽주의는 때로 성장의 걸림돌이 될 수 있어요. 실수와 실패는 배움의 과정입니다. 자신에게 더 관대해지는 연습을 해보세요. "이 정도면 충분해"라고 스스로에게 말해주세요.',
    createdAt: new Date(Date.now() - 518400000),
    updatedAt: new Date(Date.now() - 518400000),
  },
  {
    id: 'letter-7',
    userId: 'other-user-11',
    title: '번아웃이 온 것 같아요',
    content: '일도 취미도 아무것도 하기 싫어요. 그냥 누워만 있고 싶어요.',
    isPrivate: false,
    aiResponse: '번아웃의 징후가 보이네요. 지금은 쉬어야 할 때입니다. 자신을 탓하지 말고, 충분한 휴식을 취하세요. 필요하다면 전문가의 도움을 받는 것도 좋은 선택입니다.',
    createdAt: new Date(Date.now() - 604800000),
    updatedAt: new Date(Date.now() - 604800000),
  },
];

export const mockPosts: Post[] = [
  {
    id: 'post-1',
    userId: 'mock-user-1',
    authorName: '데모 사용자',
    category: 'challenge',
    title: '7일 연속 출석 달성! 🎉',
    content: '드디어 7일 연속 출석에 성공했어요! 매일 꾸준히 하니까 정말 뿌듯하네요.',
    likes: 15,
    comments: 3, // 실제 댓글: comment-1, comment-2, comment-3
    isAnonymous: false,
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'post-2',
    userId: 'other-user-1',
    authorName: '익명',
    category: 'concern',
    title: '불면증으로 고민입니다',
    content: '요즘 잠을 잘 못 자서 너무 힘들어요. 여러분은 어떻게 극복하셨나요?',
    likes: 8,
    comments: 5, // 실제 댓글: comment-4, 5, 6, 7, 8
    isAnonymous: true,
    createdAt: new Date(Date.now() - 7200000),
  },
  {
    id: 'post-3',
    userId: 'other-user-2',
    authorName: '행복한하루',
    category: 'info',
    title: '명상 앱 추천드려요',
    content: 'Headspace 앱 정말 좋아요. 초보자도 쉽게 따라할 수 있어요.',
    likes: 12,
    comments: 2, // 실제 댓글: comment-9, 10
    isAnonymous: false,
    createdAt: new Date(Date.now() - 10800000),
  },
  {
    id: 'post-4',
    userId: 'other-user-3',
    authorName: '마음챙김',
    category: 'review',
    title: 'AI 코치 진짜 도움돼요',
    content: '처음엔 반신반의했는데, AI 코치와 대화하니까 마음이 한결 가벼워졌어요.',
    likes: 20,
    comments: 3, // 실제 댓글: comment-11, 12, 13
    isAnonymous: false,
    createdAt: new Date(Date.now() - 14400000),
  },
  {
    id: 'post-5',
    userId: 'other-user-4',
    authorName: '긍정에너지',
    category: 'challenge',
    title: '30일 감사 일기 챌린지 시작!',
    content: '오늘부터 한 달 동안 매일 감사한 일 3가지씩 적어보려고 해요. 함께 하실 분?',
    likes: 28,
    comments: 0,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 18000000),
  },
  {
    id: 'post-6',
    userId: 'other-user-5',
    authorName: '익명',
    category: 'concern',
    title: '직장 스트레스가 너무 심해요',
    content: '업무량도 많고 상사와의 관계도 안 좋아서 매일이 힘들어요. 퇴사를 고민 중인데...',
    likes: 35,
    comments: 0,
    isAnonymous: true,
    createdAt: new Date(Date.now() - 21600000),
  },
  {
    id: 'post-7',
    userId: 'other-user-6',
    authorName: '요가쌤',
    category: 'info',
    title: '아침 요가 루틴 추천',
    content: '아침에 10분만 요가하면 하루가 달라져요! 초보자도 쉽게 따라할 수 있는 스트레칭 위주 루틴 공유합니다.',
    likes: 24,
    comments: 0,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 25200000),
  },
  {
    id: 'post-8',
    userId: 'other-user-7',
    authorName: '힐링중',
    category: 'review',
    title: '미션 시스템이 동기부여가 되네요',
    content: '작은 미션들을 하나씩 완수하면서 성취감을 느끼고 있어요. 특히 물 8잔 마시기가 건강에도 좋은 것 같아요!',
    likes: 17,
    comments: 0,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 28800000),
  },
  {
    id: 'post-9',
    userId: 'other-user-8',
    authorName: '익명',
    category: 'concern',
    title: '우울감이 점점 심해지는 것 같아요',
    content: '아침에 일어나기가 너무 힘들고 아무것도 하기 싫어요. 병원을 가야 할까요?',
    likes: 42,
    comments: 0,
    isAnonymous: true,
    createdAt: new Date(Date.now() - 32400000),
  },
  {
    id: 'post-10',
    userId: 'other-user-9',
    authorName: '독서광',
    category: 'info',
    title: '마음 치유에 도움되는 책 추천',
    content: '최근에 읽은 "당신이 옳다" 정말 좋았어요. 자기 긍정에 대한 내용인데 위로가 많이 됐습니다.',
    likes: 21,
    comments: 0,
    isAnonymous: false,
    createdAt: new Date(Date.now() - 36000000),
  },
];

export const mockComments: Comment[] = [
  {
    id: 'comment-1',
    postId: 'post-1',
    userId: 'other-user-1',
    authorName: '응원해요',
    content: '축하드려요! 저도 열심히 해볼게요!',
    isAnonymous: false,
    createdAt: new Date(Date.now() - 3000000),
  },
  {
    id: 'comment-2',
    postId: 'post-1',
    authorName: '익명',
    userId: 'other-user-2',
    content: '대단하세요! 꾸준함이 최고예요',
    isAnonymous: true,
    createdAt: new Date(Date.now() - 2400000),
  },
  {
    id: 'comment-3',
    postId: 'post-1',
    userId: 'other-user-3',
    authorName: '화이팅',
    content: '저도 오늘부터 시작해봐야겠어요!',
    isAnonymous: false,
    createdAt: new Date(Date.now() - 1800000),
  },
  {
    id: 'comment-4',
    postId: 'post-2',
    userId: 'other-user-4',
    authorName: '같은고민',
    content: '저도 불면증 있었는데, 자기 전 폰 안 보는게 도움됐어요',
    isAnonymous: false,
    createdAt: new Date(Date.now() - 6000000),
  },
  {
    id: 'comment-5',
    postId: 'post-2',
    userId: 'other-user-5',
    authorName: '익명',
    content: '명상 앱 써보세요. 잠들기 전 10분만 해도 효과 있어요',
    isAnonymous: true,
    createdAt: new Date(Date.now() - 5400000),
  },
  {
    id: 'comment-6',
    postId: 'post-2',
    userId: 'other-user-6',
    authorName: '수면전문가',
    content: '카페인은 오후 2시 이후로는 끊으시고, 규칙적인 수면 시간 지키세요',
    isAnonymous: false,
    createdAt: new Date(Date.now() - 4800000),
  },
  {
    id: 'comment-7',
    postId: 'post-2',
    userId: 'other-user-7',
    authorName: '익명',
    content: '저도 그랬는데 병원 가봤더니 수면제 처방받았어요',
    isAnonymous: true,
    createdAt: new Date(Date.now() - 4200000),
  },
  {
    id: 'comment-8',
    postId: 'post-2',
    userId: 'other-user-8',
    authorName: '밤새',
    content: '공감돼요ㅠㅠ 저도 요즘 새벽 3시까지 뒤척여요',
    isAnonymous: false,
    createdAt: new Date(Date.now() - 3600000),
  },
  {
    id: 'comment-9',
    postId: 'post-3',
    userId: 'other-user-9',
    authorName: '익명',
    content: '오 저도 써봐야겠어요! 정보 감사합니다',
    isAnonymous: true,
    createdAt: new Date(Date.now() - 9000000),
  },
  {
    id: 'comment-10',
    postId: 'post-3',
    userId: 'other-user-10',
    authorName: '명상초보',
    content: '무료인가요? 한글 지원되나요?',
    isAnonymous: false,
    createdAt: new Date(Date.now() - 8400000),
  },
  {
    id: 'comment-11',
    postId: 'post-4',
    userId: 'other-user-11',
    authorName: '익명',
    content: '진짜요? 저도 한번 써봐야겠어요',
    isAnonymous: true,
    createdAt: new Date(Date.now() - 12000000),
  },
  {
    id: 'comment-12',
    postId: 'post-4',
    userId: 'other-user-12',
    authorName: '호기심',
    content: 'AI 코치가 뭘 도와주나요?',
    isAnonymous: false,
    createdAt: new Date(Date.now() - 11400000),
  },
  {
    id: 'comment-13',
    postId: 'post-4',
    userId: 'mock-user-1',
    authorName: '데모 사용자',
    content: '편지 형식으로 고민을 쓰면 따뜻한 답변을 해줘요',
    isAnonymous: false,
    createdAt: new Date(Date.now() - 10800000),
  },
];

export const mockQuotes = [
  {
    id: 'quote-1',
    text: '마음이 평온할 때, 당신은 가장 강력한 당신이 됩니다.',
    author: '익명',
  },
  {
    id: 'quote-2',
    text: '오늘 하루도 충분히 잘하고 있습니다.',
    author: '자기 자신에게',
  },
  {
    id: 'quote-3',
    text: '작은 진전도 진전입니다. 스스로를 축하하세요.',
    author: '긍정의 말',
  },
  {
    id: 'quote-4',
    text: '당신은 당신이 생각하는 것보다 훨씬 강합니다.',
    author: 'A.A. 밀른',
  },
  {
    id: 'quote-5',
    text: '완벽한 하루는 없습니다. 하지만 매일 완벽한 순간은 있습니다.',
    author: '익명',
  },
  {
    id: 'quote-6',
    text: '휴식은 게으름이 아니라, 자기 자신을 위한 투자입니다.',
    author: '오프라 윈프리',
  },
  {
    id: 'quote-7',
    text: '스스로에게 친절하세요. 당신도 노력하고 있습니다.',
    author: '자기 돌봄',
  },
];

export const mockDiaries = [
  {
    id: 'diary-1',
    userId: 'mock-user-1',
    content: '오늘은 날씨가 좋아서 기분이 좋았다. 친구와 오랜만에 만나서 수다를 떨었는데 정말 즐거웠다.',
    emotion: 'happy' as const,
    date: new Date(Date.now() - 86400000),
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'diary-2',
    userId: 'mock-user-1',
    content: '새로운 프로젝트를 시작했다. 조금 걱정되지만 최선을 다해보자.',
    emotion: 'anxious' as const,
    date: new Date(Date.now() - 172800000),
    createdAt: new Date(Date.now() - 172800000),
  },
  {
    id: 'diary-3',
    userId: 'mock-user-1',
    content: '명상을 10분 했더니 마음이 한결 편안해졌다. 앞으로도 계속 해봐야겠다.',
    emotion: 'calm' as const,
    date: new Date(Date.now() - 259200000),
    createdAt: new Date(Date.now() - 259200000),
  },
  {
    id: 'diary-4',
    userId: 'mock-user-1',
    content: '오늘 출근길에 예쁜 꽃을 봤다. 작은 것에서 행복을 느낄 수 있다는 게 감사하다.',
    emotion: 'happy' as const,
    date: new Date(Date.now() - 345600000),
    createdAt: new Date(Date.now() - 345600000),
  },
  {
    id: 'diary-5',
    userId: 'mock-user-1',
    content: '업무가 힘들었지만 동료의 칭찬 한마디에 힘이 났다. 따뜻한 말의 힘은 정말 대단하다.',
    emotion: 'stressed' as const,
    date: new Date(Date.now() - 432000000),
    createdAt: new Date(Date.now() - 432000000),
  },
  {
    id: 'diary-6',
    userId: 'mock-user-1',
    content: '요가 수업을 듣고 왔다. 몸이 많이 풀렸고 마음도 한결 가벼워진 기분이다.',
    emotion: 'calm' as const,
    date: new Date(Date.now() - 518400000),
    createdAt: new Date(Date.now() - 518400000),
  },
  {
    id: 'diary-7',
    userId: 'mock-user-1',
    content: '오늘은 좀 우울했다. 이유는 모르겠지만 그럴 수도 있다고 생각하니 마음이 편해졌다.',
    emotion: 'sad' as const,
    date: new Date(Date.now() - 604800000),
    createdAt: new Date(Date.now() - 604800000),
  },
  {
    id: 'diary-8',
    userId: 'mock-user-1',
    content: '책을 읽으며 조용한 시간을 보냈다. 나만의 시간이 이렇게 소중한 줄 몰랐다.',
    emotion: 'calm' as const,
    date: new Date(Date.now() - 691200000),
    createdAt: new Date(Date.now() - 691200000),
  },
  {
    id: 'diary-9',
    userId: 'mock-user-1',
    content: '가족과 저녁을 먹으며 많은 이야기를 나눴다. 사소한 일상이 가장 큰 행복이다.',
    emotion: 'happy' as const,
    date: new Date(Date.now() - 777600000),
    createdAt: new Date(Date.now() - 777600000),
  },
  {
    id: 'diary-10',
    userId: 'mock-user-1',
    content: '오늘의 나에게 고생했다고, 충분히 잘하고 있다고 말해주고 싶다.',
    emotion: 'calm' as const,
    date: new Date(Date.now() - 864000000),
    createdAt: new Date(Date.now() - 864000000),
  },
];

export const mockAttendance = [
  { userId: 'mock-user-1', date: new Date(), checked: true },
  { userId: 'mock-user-1', date: new Date(Date.now() - 86400000), checked: true },
  { userId: 'mock-user-1', date: new Date(Date.now() - 172800000), checked: true },
  { userId: 'mock-user-1', date: new Date(Date.now() - 259200000), checked: true },
  { userId: 'mock-user-1', date: new Date(Date.now() - 345600000), checked: true },
  { userId: 'mock-user-1', date: new Date(Date.now() - 432000000), checked: true },
  { userId: 'mock-user-1', date: new Date(Date.now() - 518400000), checked: true },
  { userId: 'mock-user-1', date: new Date(Date.now() - 604800000), checked: false },
  { userId: 'mock-user-1', date: new Date(Date.now() - 691200000), checked: true },
  { userId: 'mock-user-1', date: new Date(Date.now() - 777600000), checked: true },
];

export const mockAICoaches = [
  {
    id: 'luna',
    name: '루나',
    emoji: '🧘',
    color: 'from-yellow-400 to-orange-500',
    personality: '따뜻하고 공감적인',
    description: '언제나 당신의 이야기를 들을 준비가 되어있어요',
    style: '공감과 위로를 중심으로 따뜻하게 대화합니다',
  },
  {
    id: 'minsoo',
    name: '민수',
    emoji: '🌟',
    color: 'from-blue-400 to-indigo-500',
    personality: '논리적이고 실용적인',
    description: '구체적인 해결책을 함께 찾아드려요',
    style: '실용적인 조언과 구체적인 행동 계획을 제시합니다',
  },
  {
    id: 'haneul',
    name: '하늘',
    emoji: '🌸',
    color: 'from-pink-400 to-purple-500',
    personality: '긍정적이고 활기찬',
    description: '밝은 에너지로 함께 성장해요',
    style: '긍정적인 시각과 희망적인 메시지를 전달합니다',
  },
];

export const mockContents = [
  {
    id: 'content-1',
    type: 'tip',
    category: '명상',
    title: '💡 오늘의 한 줄 상식',
    content: '하루 15분의 명상은 스트레스 호르몬을 30% 감소시킵니다.',
    link: null,
  },
  {
    id: 'content-2',
    type: 'newsletter',
    category: '글귀',
    title: '📰 이번 주 뉴스레터',
    content: '정신건강을 위한 5가지 습관',
    link: 'https://example.com/newsletter',
  },
  {
    id: 'content-3',
    type: 'music',
    category: '음악',
    title: '🎵 명상 음악',
    content: '집중력 향상을 위한 바이노럴 비트',
    link: 'https://example.com/music',
  },
  {
    id: 'content-4',
    type: 'sns',
    category: '글귀',
    title: '📱 인기 SNS 게시글',
    content: '"자기 자신에게 친절하세요" - @mindfulness_daily',
    link: 'https://example.com/sns',
  },
  {
    id: 'content-5',
    type: 'guide',
    category: '명상',
    title: '🎯 명상 가이드',
    content: '초보자를 위한 5분 호흡 명상',
    link: 'https://example.com/meditation-guide',
  },
  {
    id: 'content-6',
    type: 'video',
    category: '영상',
    title: '🎬 스트레스 해소 영상',
    content: '3분 만에 긴장을 풀어주는 이완 운동',
    link: 'https://example.com/stress-relief',
  },
  {
    id: 'content-7',
    type: 'music',
    category: '음악',
    title: '🌙 수면 음악',
    content: '깊은 수면을 위한 백색 소음',
    link: 'https://example.com/sleep-music',
  },
  {
    id: 'content-8',
    type: 'tip',
    category: '글귀',
    title: '✨ 긍정 확언',
    content: '오늘 하루도 충분히 잘하고 있습니다',
    link: null,
  },
  {
    id: 'content-9',
    type: 'guide',
    category: '명상',
    title: '🌿 마음챙김 연습',
    content: '일상에서 실천하는 마음챙김 5가지 방법',
    link: 'https://example.com/mindfulness',
  },
  {
    id: 'content-10',
    type: 'video',
    category: '영상',
    title: '🧘‍♀️ 요가 루틴',
    content: '아침 10분 요가로 하루를 시작하세요',
    link: 'https://example.com/morning-yoga',
  },
  {
    id: 'content-11',
    type: 'music',
    category: '음악',
    title: '🎶 자연의 소리',
    content: '숲속 새소리와 함께하는 평온한 시간',
    link: 'https://example.com/nature-sounds',
  },
  {
    id: 'content-12',
    type: 'tip',
    category: '글귀',
    title: '💫 오늘의 명언',
    content: '걱정은 내일의 슬픔을 가져가지 못하고, 오늘의 힘만 빼앗아갑니다.',
    link: null,
  },
  {
    id: 'content-13',
    type: 'video',
    category: '영상',
    title: '🌅 아침 스트레칭',
    content: '하루를 시작하는 5분 스트레칭 루틴',
    link: 'https://example.com/morning-stretch',
  },
  {
    id: 'content-14',
    type: 'guide',
    category: '운동',
    title: '🚶‍♀️ 걷기 명상',
    content: '일상 속에서 실천하는 움직이는 명상',
    link: 'https://example.com/walking-meditation',
  },
  {
    id: 'content-15',
    type: 'tip',
    category: '글귀',
    title: '🌸 감사 일기',
    content: '매일 3가지 감사한 일을 적어보세요. 행복이 찾아옵니다.',
    link: null,
  },
  {
    id: 'content-16',
    type: 'music',
    category: '음악',
    title: '🎹 피아노 힐링',
    content: '부드러운 피아노 선율과 함께하는 힐링 타임',
    link: 'https://example.com/piano-healing',
  },
  {
    id: 'content-17',
    type: 'video',
    category: '영상',
    title: '🌊 ASMR 파도 소리',
    content: '해변의 파도 소리로 마음의 평화를 찾아보세요',
    link: 'https://example.com/wave-asmr',
  },
  {
    id: 'content-18',
    type: 'guide',
    category: '명상',
    title: '🧘 바디 스캔 명상',
    content: '몸과 마음의 긴장을 풀어주는 바디 스캔 가이드',
    link: 'https://example.com/body-scan',
  },
  {
    id: 'content-19',
    type: 'tip',
    category: '글귀',
    title: '🌟 자기 돌봄',
    content: '자신을 돌보는 것은 이기적인 것이 아니라 필수입니다.',
    link: null,
  },
  {
    id: 'content-20',
    type: 'video',
    category: '운동',
    title: '🏃‍♂️ 가벼운 홈 운동',
    content: '집에서 하는 20분 홈 트레이닝',
    link: 'https://example.com/home-workout',
  },
  {
    id: 'content-21',
    type: 'music',
    category: '음악',
    title: '🎸 어쿠스틱 카페 음악',
    content: '여유로운 오후를 위한 카페 BGM',
    link: 'https://example.com/cafe-music',
  },
  {
    id: 'content-22',
    type: 'tip',
    category: '글귀',
    title: '💝 자기 긍정',
    content: '나는 있는 그대로도 충분히 가치 있는 사람입니다.',
    link: null,
  },
];

export const mockNotices = [
  {
    id: 'notice-1',
    title: '서비스 점검 안내',
    content: '2025년 10월 5일 02:00 ~ 04:00 서비스 점검이 예정되어 있습니다.',
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    id: 'notice-2',
    title: '새로운 기능 업데이트',
    content: '커뮤니티 검색 기능이 추가되었습니다!',
    createdAt: new Date(Date.now() - 172800000),
  },
];

export const mockFAQs = [
  {
    id: 'faq-1',
    question: 'AI 코치는 어떻게 작동하나요?',
    answer: 'AI 코치는 GPT-4 기반으로 작동하며, 당신의 고민을 듣고 따뜻한 조언을 제공합니다.',
  },
  {
    id: 'faq-2',
    question: '비공개 편지는 다른 사람이 볼 수 없나요?',
    answer: '네, 비공개로 설정한 편지는 오직 본인만 볼 수 있습니다.',
  },
  {
    id: 'faq-3',
    question: '출석 연속 기록이 끊기면 어떻게 되나요?',
    answer: '연속 기록은 초기화되지만, 총 출석일수는 계속 누적됩니다.',
  },
];
